#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

import mujoco
import numpy as np


FIELD_TO_BODY = {
    "left_hand_pose": "left_wrist_yaw_link",
    "right_hand_pose": "right_wrist_yaw_link",
    "left_foot_pose": "left_ankle_roll_link",
    "right_foot_pose": "right_ankle_roll_link",
}


def kimodo_to_mujoco_xyz(xyz_k: np.ndarray) -> np.ndarray:
    """Convert Kimodo world coords (y-up, z-forward) to MuJoCo coords (z-up, x-forward)."""
    # From kimodo/exports/mujoco.py:
    # [x_m, y_m, z_m] = [z_k, x_k, y_k]
    return np.asarray([xyz_k[2], xyz_k[0], xyz_k[1]], dtype=np.float64)


def parse_args():
    parser = argparse.ArgumentParser(description="Check ee-pose constraints against MuJoCo qpos CSV results.")
    parser.add_argument("--csv", required=True, help="Path to MuJoCo qpos CSV generated by Kimodo G1.")
    parser.add_argument("--constraints", required=True, help="Path to constraints.json (ee-pose format).")
    parser.add_argument(
        "--xml",
        default="kimodo/assets/skeletons/g1skel34/xml/g1.xml",
        help="Path to G1 MuJoCo XML (default: kimodo/assets/skeletons/g1skel34/xml/g1.xml).",
    )
    return parser.parse_args()


def load_ee_pose_constraints(path: str):
    with open(path, "r", encoding="utf-8") as f:
        items = json.load(f)
    ee_items = [x for x in items if x.get("type") == "ee-pose"]
    if not ee_items:
        raise ValueError(f"No ee-pose constraints found in: {path}")
    return ee_items


def main():
    args = parse_args()
    csv_path = Path(args.csv)
    constraints_path = Path(args.constraints)
    xml_path = Path(args.xml)

    if not csv_path.exists():
        raise FileNotFoundError(f"CSV not found: {csv_path}")
    if not constraints_path.exists():
        raise FileNotFoundError(f"Constraints not found: {constraints_path}")
    if not xml_path.exists():
        raise FileNotFoundError(f"MuJoCo XML not found: {xml_path}")

    qpos = np.loadtxt(str(csv_path), delimiter=",")
    if qpos.ndim == 1:
        qpos = qpos[None, :]

    model = mujoco.MjModel.from_xml_path(str(xml_path))
    data = mujoco.MjData(model)

    ee_items = load_ee_pose_constraints(str(constraints_path))

    print(f"CSV: {csv_path}")
    print(f"Constraints: {constraints_path}")
    print(f"XML: {xml_path}")
    print(f"Frames in CSV: {len(qpos)}")
    print("")

    all_errors = []
    row_count = 0
    print("frame,ee,expected_xyz,actual_xyz,error_m")

    for item in ee_items:
        frame_indices = item.get("frame_indices", [])
        for local_i, frame_idx in enumerate(frame_indices):
            if frame_idx < 0 or frame_idx >= len(qpos):
                print(f"WARNING: frame {frame_idx} out of range, skipped")
                continue

            data.qpos[:] = qpos[frame_idx]
            mujoco.mj_forward(model, data)

            for field, body_name in FIELD_TO_BODY.items():
                poses = item.get(field)
                if not poses:
                    continue
                expected_k = np.asarray(poses[local_i][:3], dtype=np.float64)
                expected = kimodo_to_mujoco_xyz(expected_k)
                body_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, body_name)
                actual = np.asarray(data.xpos[body_id], dtype=np.float64)
                err = float(np.linalg.norm(actual - expected))
                all_errors.append(err)
                row_count += 1
                print(
                    f"{frame_idx},{field},{np.round(expected, 6).tolist()},"
                    f"{np.round(actual, 6).tolist()},{err:.6f}"
                )

    if row_count == 0:
        print("\nNo ee rows were evaluated (check constraint fields).")
        return

    print("")
    print("Summary")
    print(f"rows: {row_count}")
    print(f"mean_error_m: {np.mean(all_errors):.6f}")
    print(f"max_error_m: {np.max(all_errors):.6f}")
    print(f"min_error_m: {np.min(all_errors):.6f}")


if __name__ == "__main__":
    main()
